# Default configuration file which is copied in '~/.celexta/config/default_config.yaml'
# on any new installation of Celexta (or when the file dosen't exist).
# Any modification should be done to 'user_config.yaml' which will override the values
# found here

filenames:
  last_opened: '~'

# Logging configuration
# Only change this if you know what you are doing
logging:
  # Use null for no log file
  log_file: '~/.celexta/logs/celexta.log'
  # log_file: null
  # Can be 'DEBUG', 'INFO', 'WARNING'
  log_level: 'DEBUG'