# User configuration file which will override 'default_config.yaml'
# This file is used to save the state of certain variables used by Celexta

files:
  last_opened: '~'
  default_gcn_authors: 'GCN_authors.csv'